### model
model_type: vlm_seg
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
seg_decoder_path: facebook/mask2former-swin-base
image_max_pixels: 262144
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
deepseed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: your_seg_dataset
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2

### output
output_dir: saves/vlm_seg/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null 